#
# Copyright 2025 OpenAirLink Contributors
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

##################################################
# RFNoC Block Sources - Complex Sparse FIR Filter
##################################################
RFNOC_OOT_SRCS += $(addprefix $(dir $(abspath $(lastword $(MAKEFILE_LIST)))), \
rfnoc_complex_sparse_fir_regs.vh \
axi_complex_sparse_fir.v \
axi_complex_sparse_fir_complex.v \
rfnoc_block_complex_sparse_fir.v \
noc_shell_complex_sparse_fir.v \
)
